"""Externí audity — konstanty EA-0."""

from __future__ import annotations

from core.shared.constants import ENTITY_EXTERNAL_AUDIT

EXTERNAL_AUDIT_TYPE_RECERTIFICATION = "recertification"
EXTERNAL_AUDIT_TYPE_SURVEILLANCE = "surveillance"
EXTERNAL_AUDIT_TYPES = frozenset(
    {
        EXTERNAL_AUDIT_TYPE_RECERTIFICATION,
        EXTERNAL_AUDIT_TYPE_SURVEILLANCE,
    }
)
EXTERNAL_AUDIT_TYPE_LABELS: dict[str, str] = {
    EXTERNAL_AUDIT_TYPE_RECERTIFICATION: "Recertifikační",
    EXTERNAL_AUDIT_TYPE_SURVEILLANCE: "Dozorový",
}

EXTERNAL_AUDIT_STATUS_PLANNED = "planned"
EXTERNAL_AUDIT_STATUS_IN_PROGRESS = "in_progress"
EXTERNAL_AUDIT_STATUS_CLOSED = "closed"
EXTERNAL_AUDIT_STATUS_CANCELLED = "cancelled"
EXTERNAL_AUDIT_STATUSES = frozenset(
    {
        EXTERNAL_AUDIT_STATUS_PLANNED,
        EXTERNAL_AUDIT_STATUS_IN_PROGRESS,
        EXTERNAL_AUDIT_STATUS_CLOSED,
        EXTERNAL_AUDIT_STATUS_CANCELLED,
    }
)
EXTERNAL_AUDIT_STATUS_LABELS: dict[str, str] = {
    EXTERNAL_AUDIT_STATUS_PLANNED: "Naplánováno",
    EXTERNAL_AUDIT_STATUS_IN_PROGRESS: "Probíhá",
    EXTERNAL_AUDIT_STATUS_CLOSED: "Uzavřeno",
    EXTERNAL_AUDIT_STATUS_CANCELLED: "Zrušeno",
}

EXTERNAL_AUDIT_PARTICIPANT_ROLE_EXTERNAL_AUDITOR = "external_auditor"
EXTERNAL_AUDIT_PARTICIPANT_ROLE_COMPANY_REPRESENTATIVE = "company_representative"
EXTERNAL_AUDIT_PARTICIPANT_ROLE_INVITED_PERSON = "invited_person"
EXTERNAL_AUDIT_PARTICIPANT_ROLES = frozenset(
    {
        EXTERNAL_AUDIT_PARTICIPANT_ROLE_EXTERNAL_AUDITOR,
        EXTERNAL_AUDIT_PARTICIPANT_ROLE_COMPANY_REPRESENTATIVE,
        EXTERNAL_AUDIT_PARTICIPANT_ROLE_INVITED_PERSON,
    }
)
EXTERNAL_AUDIT_PARTICIPANT_ROLE_LABELS: dict[str, str] = {
    EXTERNAL_AUDIT_PARTICIPANT_ROLE_EXTERNAL_AUDITOR: "Externí auditor",
    EXTERNAL_AUDIT_PARTICIPANT_ROLE_COMPANY_REPRESENTATIVE: "Zástupce společnosti",
    EXTERNAL_AUDIT_PARTICIPANT_ROLE_INVITED_PERSON: "Přizvaná osoba",
}

EXTERNAL_AUDIT_SOURCE_PERSON = "person"
EXTERNAL_AUDIT_SOURCE_THP_WORKER = "thp_worker"
EXTERNAL_AUDIT_SOURCE_TYPES = frozenset(
    {
        EXTERNAL_AUDIT_SOURCE_PERSON,
        EXTERNAL_AUDIT_SOURCE_THP_WORKER,
    }
)

# Role → povolený source_type
EXTERNAL_AUDIT_ROLE_SOURCE_TYPES: dict[str, str] = {
    EXTERNAL_AUDIT_PARTICIPANT_ROLE_EXTERNAL_AUDITOR: EXTERNAL_AUDIT_SOURCE_PERSON,
    EXTERNAL_AUDIT_PARTICIPANT_ROLE_COMPANY_REPRESENTATIVE: EXTERNAL_AUDIT_SOURCE_THP_WORKER,
    EXTERNAL_AUDIT_PARTICIPANT_ROLE_INVITED_PERSON: EXTERNAL_AUDIT_SOURCE_PERSON,
}

EXTERNAL_AUDIT_FINDING_TYPE_NONCONFORMITY = "nonconformity"
EXTERNAL_AUDIT_FINDING_TYPE_IMPROVEMENT = "improvement_opportunity"
EXTERNAL_AUDIT_FINDING_TYPE_STRENGTH = "strength"
EXTERNAL_AUDIT_FINDING_TYPES = frozenset(
    {
        EXTERNAL_AUDIT_FINDING_TYPE_NONCONFORMITY,
        EXTERNAL_AUDIT_FINDING_TYPE_IMPROVEMENT,
        EXTERNAL_AUDIT_FINDING_TYPE_STRENGTH,
    }
)
EXTERNAL_AUDIT_FINDING_TYPE_LABELS: dict[str, str] = {
    EXTERNAL_AUDIT_FINDING_TYPE_NONCONFORMITY: "Neshoda",
    EXTERNAL_AUDIT_FINDING_TYPE_IMPROVEMENT: "PKZ / Příležitost ke zlepšení",
    EXTERNAL_AUDIT_FINDING_TYPE_STRENGTH: "Silná stránka",
}

EXTERNAL_AUDIT_FINDING_STATUS_OPEN = "open"
EXTERNAL_AUDIT_FINDING_STATUS_IN_PROGRESS = "in_progress"
EXTERNAL_AUDIT_FINDING_STATUS_RESOLVED = "resolved"
EXTERNAL_AUDIT_FINDING_STATUS_RECORDED = "recorded"  # pouze silná stránka

EXTERNAL_AUDIT_FINDING_ACTIONABLE_STATUSES = frozenset(
    {
        EXTERNAL_AUDIT_FINDING_STATUS_OPEN,
        EXTERNAL_AUDIT_FINDING_STATUS_IN_PROGRESS,
        EXTERNAL_AUDIT_FINDING_STATUS_RESOLVED,
    }
)
EXTERNAL_AUDIT_FINDING_STATUS_LABELS: dict[str, str] = {
    EXTERNAL_AUDIT_FINDING_STATUS_OPEN: "Otevřeno",
    EXTERNAL_AUDIT_FINDING_STATUS_IN_PROGRESS: "Řeší se",
    EXTERNAL_AUDIT_FINDING_STATUS_RESOLVED: "Vypořádáno",
    EXTERNAL_AUDIT_FINDING_STATUS_RECORDED: "Zaznamenáno",
}
