ENTITY_AUDITY = "audity"
ENTITY_PROVERKY = "proverky"
ENTITY_ACCIDENT = "accident"
ENTITY_MU_INVESTIGATION = "mu_investigation"

ENTITY_FINDING = "finding"
ENTITY_TASK = "task"
ENTITY_LEGAL_REQUIREMENT = "legal_requirement"
ENTITY_LEGAL_CHANGE = "legal_change"

ENTITY_AUDIT = "audit"
ENTITY_INSPECTION = "inspection"
ENTITY_RISK = "risk"
ENTITY_DIRECTIVE = "directive"
ENTITY_TRAINING = "training"
ENTITY_PPE = "ppe"
ENTITY_CHEMICAL = "chemical"

LINK_RELATED = "related"
LINK_REQUIRES = "requires"
LINK_EVIDENCE = "evidence"
LINK_CONTROL_MEASURE = "control_measure"
LINK_LEGAL_BASIS = "legal_basis"

VALID_ENTITY_TYPES = frozenset(
    {
        ENTITY_AUDITY,
        ENTITY_PROVERKY,
        ENTITY_ACCIDENT,
        ENTITY_MU_INVESTIGATION,
        ENTITY_FINDING,
        ENTITY_TASK,
        ENTITY_LEGAL_REQUIREMENT,
        ENTITY_LEGAL_CHANGE,
        ENTITY_AUDIT,
        ENTITY_INSPECTION,
        ENTITY_RISK,
        ENTITY_DIRECTIVE,
        ENTITY_TRAINING,
        ENTITY_PPE,
        ENTITY_CHEMICAL,
    }
)

VALID_LINK_ENTITY_TYPES = frozenset(
    {
        ENTITY_LEGAL_REQUIREMENT,
        ENTITY_LEGAL_CHANGE,
        ENTITY_TASK,
        ENTITY_AUDIT,
        ENTITY_INSPECTION,
        ENTITY_RISK,
        ENTITY_DIRECTIVE,
        ENTITY_TRAINING,
        ENTITY_PPE,
        ENTITY_CHEMICAL,
        ENTITY_ACCIDENT,
    }
)

VALID_LINK_TYPES = frozenset(
    {
        LINK_RELATED,
        LINK_REQUIRES,
        LINK_EVIDENCE,
        LINK_CONTROL_MEASURE,
        LINK_LEGAL_BASIS,
    }
)

ENTITY_TYPE_LABELS: dict[str, str] = {
    ENTITY_LEGAL_REQUIREMENT: "Právní požadavek",
    ENTITY_LEGAL_CHANGE: "Změna legislativy",
    ENTITY_TASK: "Úkol",
    ENTITY_AUDIT: "Audit",
    ENTITY_INSPECTION: "Kontrola / prověrka",
    ENTITY_RISK: "Riziko",
    ENTITY_DIRECTIVE: "Interní směrnice",
    ENTITY_TRAINING: "Školení",
    ENTITY_PPE: "OOPP",
    ENTITY_CHEMICAL: "Chemická látka",
    ENTITY_ACCIDENT: "Úraz",
    ENTITY_AUDITY: "Audit systému",
    ENTITY_PROVERKY: "Prověrka BOZP",
    ENTITY_MU_INVESTIGATION: "Vyšetřování MU",
    ENTITY_FINDING: "Zjištění",
}

LINK_TYPE_LABELS: dict[str, str] = {
    LINK_RELATED: "Související",
    LINK_REQUIRES: "Vyžaduje",
    LINK_EVIDENCE: "Důkaz / evidence",
    LINK_CONTROL_MEASURE: "Kontrolní opatření",
    LINK_LEGAL_BASIS: "Právní základ",
}

FINDING_TYPE_ZAVADA = "zavada"
FINDING_TYPE_NEDOSTATEK = "nedostatek"
FINDING_TYPE_PRILEZITOST = "prilezitost_zlepseni"
FINDING_TYPE_NESHODA = "neshoda"
FINDING_TYPE_POZOROVANI = "pozorovani"
FINDING_TYPE_POKYN = "pokyn"
FINDING_TYPE_ZJISTENI = "zjisteni"

FINDING_TYPE_BEZPROSTREDNI_PRICINA = "bezprostredni_pricina"
FINDING_TYPE_ZAKLADNI_PRICINA = "zakladni_pricina"
FINDING_TYPE_SYSTEMOVA_PRICINA = "systemova_pricina"
FINDING_TYPE_PORUSENI_PREDPISU = "poruseni_predpisu"
FINDING_TYPE_OPATRENI = "opatreni"

VALID_FINDING_TYPES = frozenset(
    {
        FINDING_TYPE_ZAVADA,
        FINDING_TYPE_NEDOSTATEK,
        FINDING_TYPE_PRILEZITOST,
        FINDING_TYPE_NESHODA,
        FINDING_TYPE_POZOROVANI,
        FINDING_TYPE_POKYN,
        FINDING_TYPE_ZJISTENI,
        FINDING_TYPE_BEZPROSTREDNI_PRICINA,
        FINDING_TYPE_ZAKLADNI_PRICINA,
        FINDING_TYPE_SYSTEMOVA_PRICINA,
        FINDING_TYPE_PORUSENI_PREDPISU,
        FINDING_TYPE_OPATRENI,
    }
)

ACCIDENT_FINDING_TYPES = frozenset(
    {
        FINDING_TYPE_BEZPROSTREDNI_PRICINA,
        FINDING_TYPE_ZAKLADNI_PRICINA,
        FINDING_TYPE_SYSTEMOVA_PRICINA,
        FINDING_TYPE_PORUSENI_PREDPISU,
        FINDING_TYPE_OPATRENI,
    }
)

FINDING_STATUS_OTEVRENE = "otevrene"
FINDING_STATUS_V_PROCESU = "v_procesu"
FINDING_STATUS_VYPORADANO = "vyporadano"

VALID_FINDING_STATUSES = frozenset(
    {
        FINDING_STATUS_OTEVRENE,
        FINDING_STATUS_V_PROCESU,
        FINDING_STATUS_VYPORADANO,
    }
)

MAX_ENTITY_TYPE_LENGTH = 50

CONTROL_RESULT_NEKONTROLOVANO = "nekontrolovano"
CONTROL_RESULT_VYHOVUJE = "vyhovuje"
CONTROL_RESULT_VYHOVUJE_S_DOPORUCENIM = "vyhovuje_s_doporucenim"
CONTROL_RESULT_NEVYHOVUJE = "nevyhovuje"
CONTROL_RESULT_NELZE_POSOUDIT = "nelze_posoudit"

VALID_CONTROL_RESULTS = frozenset(
    {
        CONTROL_RESULT_NEKONTROLOVANO,
        CONTROL_RESULT_VYHOVUJE,
        CONTROL_RESULT_VYHOVUJE_S_DOPORUCENIM,
        CONTROL_RESULT_NEVYHOVUJE,
        CONTROL_RESULT_NELZE_POSOUDIT,
    }
)

CONTROL_RESULT_LABELS: dict[str, str] = {
    CONTROL_RESULT_NEKONTROLOVANO: "○ Nekontrolováno",
    CONTROL_RESULT_VYHOVUJE: "🟢 Vyhovuje",
    CONTROL_RESULT_VYHOVUJE_S_DOPORUCENIM: "🟡 Vyhovuje s doporučením",
    CONTROL_RESULT_NEVYHOVUJE: "🔴 Nevyhovuje",
    CONTROL_RESULT_NELZE_POSOUDIT: "⚪ Nelze posoudit",
}

CONTROL_RESULT_PARENT_ENTITY_TYPES = frozenset(
    {
        ENTITY_AUDITY,
        ENTITY_PROVERKY,
    }
)
