ENTITY_AUDITY = "audity"
ENTITY_PROVERKY = "proverky"
ENTITY_ACCIDENT = "accident"
ENTITY_MU_INVESTIGATION = "mu_investigation"

ENTITY_FINDING = "finding"
ENTITY_TASK = "task"

VALID_ENTITY_TYPES = frozenset(
    {
        ENTITY_AUDITY,
        ENTITY_PROVERKY,
        ENTITY_ACCIDENT,
        ENTITY_MU_INVESTIGATION,
        ENTITY_FINDING,
        ENTITY_TASK,
    }
)

FINDING_TYPE_ZAVADA = "zavada"
FINDING_TYPE_NEDOSTATEK = "nedostatek"
FINDING_TYPE_PRILEZITOST = "prilezitost_zlepseni"
FINDING_TYPE_POKYN = "pokyn"
FINDING_TYPE_ZJISTENI = "zjisteni"

FINDING_TYPE_BEZPROSTREDNI_PRICINA = "bezprostredni_pricina"
FINDING_TYPE_ZAKLADNI_PRICINA = "zakladni_pricina"
FINDING_TYPE_SYSTEMOVA_PRICINA = "systemova_pricina"
FINDING_TYPE_PORUSENI_PREDPISU = "poruseni_predpisu"
FINDING_TYPE_OPATRENI = "opatreni"

VALID_FINDING_TYPES = frozenset(
    {
        FINDING_TYPE_ZAVADA,
        FINDING_TYPE_NEDOSTATEK,
        FINDING_TYPE_PRILEZITOST,
        FINDING_TYPE_POKYN,
        FINDING_TYPE_ZJISTENI,
        FINDING_TYPE_BEZPROSTREDNI_PRICINA,
        FINDING_TYPE_ZAKLADNI_PRICINA,
        FINDING_TYPE_SYSTEMOVA_PRICINA,
        FINDING_TYPE_PORUSENI_PREDPISU,
        FINDING_TYPE_OPATRENI,
    }
)

ACCIDENT_FINDING_TYPES = frozenset(
    {
        FINDING_TYPE_BEZPROSTREDNI_PRICINA,
        FINDING_TYPE_ZAKLADNI_PRICINA,
        FINDING_TYPE_SYSTEMOVA_PRICINA,
        FINDING_TYPE_PORUSENI_PREDPISU,
        FINDING_TYPE_OPATRENI,
    }
)

FINDING_STATUS_OTEVRENE = "otevrene"
FINDING_STATUS_V_PROCESU = "v_procesu"
FINDING_STATUS_VYPORADANO = "vyporadano"

VALID_FINDING_STATUSES = frozenset(
    {
        FINDING_STATUS_OTEVRENE,
        FINDING_STATUS_V_PROCESU,
        FINDING_STATUS_VYPORADANO,
    }
)

MAX_ENTITY_TYPE_LENGTH = 50
