ENTITY_AUDITY = "audity"
ENTITY_PROVERKY = "proverky"
ENTITY_ACCIDENT = "accident"
ENTITY_MU_INVESTIGATION = "mu_investigation"

ENTITY_FINDING = "finding"
ENTITY_TASK = "task"
ENTITY_LEGAL_REQUIREMENT = "legal_requirement"

VALID_ENTITY_TYPES = frozenset(
    {
        ENTITY_AUDITY,
        ENTITY_PROVERKY,
        ENTITY_ACCIDENT,
        ENTITY_MU_INVESTIGATION,
        ENTITY_FINDING,
        ENTITY_TASK,
        ENTITY_LEGAL_REQUIREMENT,
    }
)

FINDING_TYPE_ZAVADA = "zavada"
FINDING_TYPE_NEDOSTATEK = "nedostatek"
FINDING_TYPE_PRILEZITOST = "prilezitost_zlepseni"
FINDING_TYPE_NESHODA = "neshoda"
FINDING_TYPE_POZOROVANI = "pozorovani"
FINDING_TYPE_POKYN = "pokyn"
FINDING_TYPE_ZJISTENI = "zjisteni"

FINDING_TYPE_BEZPROSTREDNI_PRICINA = "bezprostredni_pricina"
FINDING_TYPE_ZAKLADNI_PRICINA = "zakladni_pricina"
FINDING_TYPE_SYSTEMOVA_PRICINA = "systemova_pricina"
FINDING_TYPE_PORUSENI_PREDPISU = "poruseni_predpisu"
FINDING_TYPE_OPATRENI = "opatreni"

VALID_FINDING_TYPES = frozenset(
    {
        FINDING_TYPE_ZAVADA,
        FINDING_TYPE_NEDOSTATEK,
        FINDING_TYPE_PRILEZITOST,
        FINDING_TYPE_NESHODA,
        FINDING_TYPE_POZOROVANI,
        FINDING_TYPE_POKYN,
        FINDING_TYPE_ZJISTENI,
        FINDING_TYPE_BEZPROSTREDNI_PRICINA,
        FINDING_TYPE_ZAKLADNI_PRICINA,
        FINDING_TYPE_SYSTEMOVA_PRICINA,
        FINDING_TYPE_PORUSENI_PREDPISU,
        FINDING_TYPE_OPATRENI,
    }
)

ACCIDENT_FINDING_TYPES = frozenset(
    {
        FINDING_TYPE_BEZPROSTREDNI_PRICINA,
        FINDING_TYPE_ZAKLADNI_PRICINA,
        FINDING_TYPE_SYSTEMOVA_PRICINA,
        FINDING_TYPE_PORUSENI_PREDPISU,
        FINDING_TYPE_OPATRENI,
    }
)

FINDING_STATUS_OTEVRENE = "otevrene"
FINDING_STATUS_V_PROCESU = "v_procesu"
FINDING_STATUS_VYPORADANO = "vyporadano"

VALID_FINDING_STATUSES = frozenset(
    {
        FINDING_STATUS_OTEVRENE,
        FINDING_STATUS_V_PROCESU,
        FINDING_STATUS_VYPORADANO,
    }
)

MAX_ENTITY_TYPE_LENGTH = 50

CONTROL_RESULT_NEKONTROLOVANO = "nekontrolovano"
CONTROL_RESULT_VYHOVUJE = "vyhovuje"
CONTROL_RESULT_VYHOVUJE_S_DOPORUCENIM = "vyhovuje_s_doporucenim"
CONTROL_RESULT_NEVYHOVUJE = "nevyhovuje"
CONTROL_RESULT_NELZE_POSOUDIT = "nelze_posoudit"

VALID_CONTROL_RESULTS = frozenset(
    {
        CONTROL_RESULT_NEKONTROLOVANO,
        CONTROL_RESULT_VYHOVUJE,
        CONTROL_RESULT_VYHOVUJE_S_DOPORUCENIM,
        CONTROL_RESULT_NEVYHOVUJE,
        CONTROL_RESULT_NELZE_POSOUDIT,
    }
)

CONTROL_RESULT_LABELS: dict[str, str] = {
    CONTROL_RESULT_NEKONTROLOVANO: "○ Nekontrolováno",
    CONTROL_RESULT_VYHOVUJE: "🟢 Vyhovuje",
    CONTROL_RESULT_VYHOVUJE_S_DOPORUCENIM: "🟡 Vyhovuje s doporučením",
    CONTROL_RESULT_NEVYHOVUJE: "🔴 Nevyhovuje",
    CONTROL_RESULT_NELZE_POSOUDIT: "⚪ Nelze posoudit",
}

CONTROL_RESULT_PARENT_ENTITY_TYPES = frozenset(
    {
        ENTITY_AUDITY,
        ENTITY_PROVERKY,
    }
)
