AUDIT_STATUS_KONCEPT = "Koncept"
AUDIT_STATUS_PROBIHA = "Probíhá"
AUDIT_STATUS_DOKONCEN = "Dokončen"

DEFAULT_AUDIT_STATUS = AUDIT_STATUS_KONCEPT

VALID_AUDIT_STATUSES = frozenset(
    {
        AUDIT_STATUS_KONCEPT,
        AUDIT_STATUS_PROBIHA,
        AUDIT_STATUS_DOKONCEN,
    }
)
