"""Konstanty modulu Události (interně schuzky)."""

MODULE_KEY = "schuzky"
MODULE_NAME = "Události"
DIALOG_WINDOW_TITLE = "Událost"
LIST_WINDOW_TITLE = "Události"

STATUS_PLANNED = "Naplánováno"
STATUS_HELD = "Proběhlo"
STATUS_CLOSED = "Uzavřeno"
STATUS_CANCELLED = "Zrušeno"

MEETING_STATUSES = (
    STATUS_PLANNED,
    STATUS_HELD,
    STATUS_CLOSED,
    STATUS_CANCELLED,
)

DEFAULT_MEETING_STATUS = STATUS_PLANNED

PRIORITY_LOW = "Nízká"
PRIORITY_NORMAL = "Normální"
PRIORITY_HIGH = "Vysoká"
PRIORITY_CRITICAL = "Kritická"

MEETING_PRIORITIES = (
    PRIORITY_LOW,
    PRIORITY_NORMAL,
    PRIORITY_HIGH,
    PRIORITY_CRITICAL,
)

DEFAULT_MEETING_PRIORITY = PRIORITY_NORMAL

# Řazení priority stejně jako u Úkolů (Kritická nahoře).
MEETING_PRIORITY_RANK = {
    PRIORITY_CRITICAL: 0,
    PRIORITY_HIGH: 1,
    PRIORITY_NORMAL: 2,
    PRIORITY_LOW: 3,
}

EVENT_TYPE_MEETING = "Schůzka"
EVENT_TYPE_TRAINING = "Školení"
EVENT_TYPE_BRIEFING = "Porada"
EVENT_TYPE_DISCUSSION = "Jednání"
EVENT_TYPE_MEETING_EN = "Meeting"
EVENT_TYPE_CONSULTATION = "Konzultace"
EVENT_TYPE_WALKTHROUGH = "Kontrolní pochůzka"
EVENT_TYPE_PHONE = "Telefonát"
EVENT_TYPE_ONLINE = "Online schůzka"
EVENT_TYPE_OTHER = "Jiné"

DEFAULT_EVENT_TYPES = (
    EVENT_TYPE_MEETING,
    EVENT_TYPE_TRAINING,
    EVENT_TYPE_BRIEFING,
    EVENT_TYPE_DISCUSSION,
    EVENT_TYPE_MEETING_EN,
    EVENT_TYPE_CONSULTATION,
    EVENT_TYPE_WALKTHROUGH,
    EVENT_TYPE_PHONE,
    EVENT_TYPE_ONLINE,
    EVENT_TYPE_OTHER,
)

DEFAULT_EVENT_TYPE = EVENT_TYPE_MEETING

END_BEFORE_START_MESSAGE = "Konec události nesmí být dříve než začátek."

TAB_MEETING = "Událost"
TAB_MINUTES = "Záznam z jednání"  # legacy – nahrazeno TAB_DISCUSSION
TAB_DISCUSSION = "Zápisky"

AGENDA_ITEM_STATUS_READY = "Připraveno"
AGENDA_ITEM_STATUS_DISCUSSED = "Projednáno"
AGENDA_ITEM_STATUS_POSTPONED = "Odloženo"

AGENDA_ITEM_STATUSES = (
    AGENDA_ITEM_STATUS_READY,
    AGENDA_ITEM_STATUS_DISCUSSED,
    AGENDA_ITEM_STATUS_POSTPONED,
)

DEFAULT_AGENDA_ITEM_STATUS = AGENDA_ITEM_STATUS_READY

AGENDA_ITEM_STATUS_ICONS = {
    AGENDA_ITEM_STATUS_READY: "🟡",
    AGENDA_ITEM_STATUS_DISCUSSED: "🟢",
    AGENDA_ITEM_STATUS_POSTPONED: "🔵",
}

AGENDA_ITEM_STATUS_MENU_TITLE = "Označit jako"

AGENDA_ITEM_DIALOG_TITLE = "Bod jednání"  # legacy – dialog zrušen v MEETINGS-2c
AGENDA_ITEMS_SECTION = "Body jednání"
AGENDA_ITEMS_COUNT_TEMPLATE = "Body jednání: {count}"
AGENDA_ITEMS_EMPTY = "Zatím nejsou evidovány žádné body jednání."
AGENDA_ITEM_NONE_SELECTED = "Není vybrán žádný bod jednání."
AGENDA_SELECT_ITEM_MESSAGE = "Vyberte bod jednání."

ACTION_ADD_AGENDA_ITEM = "Přidat"
ACTION_EDIT = "Upravit"
ACTION_REMOVE = "Odebrat"
ACTION_MOVE_UP = "Nahoru"
ACTION_MOVE_DOWN = "Dolů"

SECTION_ITEM_TASKS = "Úkoly"
ACTION_ADD_TASK = "Přidat úkol"
ACTION_OPEN_TASK = "Otevřít úkol"
ACTION_UNLINK_TASK = "Odpojit od bodu"
SAVE_MEETING_BEFORE_TASK_MESSAGE = "Nejprve uložte událost."
AGENDA_ITEM_CHECK_PREFIX = "item:"

# Legacy MEETINGS-1d (sekce na úrovni schůzky zrušeny v MEETINGS-2d)
SECTION_CONCLUSION_TASKS = "Úkoly ze závěrů"
SECTION_LINKED_TASKS = "Navázané úkoly"
ACTION_CREATE_TASK = "Vytvořit úkol"
CONCLUSION_CHECK_PREFIX = "concl:"

COL_ID = 0
COL_STARTS_AT = 1
COL_TYPE = 2
COL_PRIORITY = 3
COL_TITLE = 4
COL_LOCATION = 5
COL_ORGANIZER = 6
COL_STATUS = 7

COLUMN_HEADERS = [
    "ID",
    "Datum a čas",
    "Typ",
    "Priorita",
    "Název události",
    "Místo",
    "Organizátor",
    "Stav",
]
