"""Konstanty firemní knihovny vzorů (R17a)."""

HAZARD_LIBRARY_SCOPE_ALL = "all_operations"
HAZARD_LIBRARY_SCOPE_SELECTED = "selected_operations"
HAZARD_LIBRARY_SCOPE_MANUAL = "manual"

DEFAULT_HAZARD_LIBRARY_SCOPE = HAZARD_LIBRARY_SCOPE_MANUAL

HAZARD_LIBRARY_SCOPES = (
    HAZARD_LIBRARY_SCOPE_ALL,
    HAZARD_LIBRARY_SCOPE_SELECTED,
    HAZARD_LIBRARY_SCOPE_MANUAL,
)

HAZARD_LIBRARY_SCOPE_LABELS = {
    HAZARD_LIBRARY_SCOPE_ALL: "Všechny provozy",
    HAZARD_LIBRARY_SCOPE_SELECTED: "Vybrané provozy",
    HAZARD_LIBRARY_SCOPE_MANUAL: "Bez předem určeného rozsahu",
}

HAZARD_LIBRARY_PAGE_TITLE = "Firemní knihovna"
HAZARD_LIBRARY_DIALOG_TITLE = "Vzor knihovny"

HAZARD_LIBRARY_TAB_BASICS = "Základní údaje"
HAZARD_LIBRARY_TAB_CONTENT = "Obsah vzoru"
HAZARD_LIBRARY_TAB_USAGE = "Použití"
HAZARD_LIBRARY_TAB_HISTORY = "Historie"

HAZARD_LIBRARY_PLACEHOLDER_TEXT = "Obsah bude doplněn v další fázi."

HAZARD_LIBRARY_COL_ID = 0
HAZARD_LIBRARY_COL_NAME = 1
HAZARD_LIBRARY_COL_SCOPE = 2
HAZARD_LIBRARY_COL_VERSION = 3
HAZARD_LIBRARY_COL_OPERATION_COUNT = 4
HAZARD_LIBRARY_COL_ACTIVE = 5
HAZARD_LIBRARY_COLUMN_COUNT = 6

HAZARD_LIBRARY_TABLE_HEADERS = [
    "ID",
    "Název",
    "Rozsah použití",
    "Verze",
    "Počet provozů",
    "Aktivní",
]

DEFAULT_HAZARD_LIBRARY_VERSION = 1
