"""Konstanty modulu Řízení rizik."""

MODULE_KEY = "rizeni_rizik"
MODULE_NAME = "Řízení rizik"
MODULE_DESCRIPTION = "Identifikace nebezpečí a řízení rizik na provozech a pracovištích."

HAZARD_IDENTIFICATION_STATUS_DRAFT = "draft"
HAZARD_IDENTIFICATION_STATUS_IN_PROGRESS = "in_progress"
HAZARD_IDENTIFICATION_STATUS_COMPLETED = "completed"
HAZARD_IDENTIFICATION_STATUS_ARCHIVED = "archived"

HAZARD_IDENTIFICATION_STATUSES = (
    HAZARD_IDENTIFICATION_STATUS_DRAFT,
    HAZARD_IDENTIFICATION_STATUS_IN_PROGRESS,
    HAZARD_IDENTIFICATION_STATUS_COMPLETED,
    HAZARD_IDENTIFICATION_STATUS_ARCHIVED,
)

DEFAULT_HAZARD_IDENTIFICATION_STATUS = HAZARD_IDENTIFICATION_STATUS_DRAFT

HAZARD_IDENTIFICATION_STATUS_LABELS = {
    HAZARD_IDENTIFICATION_STATUS_DRAFT: "Koncept",
    HAZARD_IDENTIFICATION_STATUS_IN_PROGRESS: "Probíhá",
    HAZARD_IDENTIFICATION_STATUS_COMPLETED: "Dokončeno",
    HAZARD_IDENTIFICATION_STATUS_ARCHIVED: "Archivováno",
}

COL_ID = 0
COL_TITLE = 1
COL_OPERATION = 2
COL_WORKPLACE = 3
COL_STARTED_AT = 4
COL_RESPONSIBLE_PERSON = 5
COL_STATUS = 6
COLUMN_COUNT = 7

TABLE_HEADERS = [
    "ID",
    "Název",
    "Provoz",
    "Pracoviště",
    "Datum zahájení",
    "Odpovědná osoba",
    "Stav",
]

TAB_BASICS = "Základní údaje"
TAB_INVENTORY = "Inventura"
TAB_HAZARDS = "Nebezpečí"
TAB_RISK_ASSESSMENT = "Posouzení rizik"
TAB_MEASURES = "Opatření"
TAB_PUBLICATION = "Publikace"
TAB_HISTORY = "Historie"

HAZARD_IDENTIFICATION_TABS = (
    TAB_BASICS,
    TAB_INVENTORY,
    TAB_HAZARDS,
    TAB_RISK_ASSESSMENT,
    TAB_MEASURES,
    TAB_PUBLICATION,
    TAB_HISTORY,
)

DIALOG_WINDOW_TITLE = "Identifikace nebezpečí"

INVENTORY_INTRO_TEXT = (
    "Zaznamenejte zařízení, činnosti, energie, látky, prostory, dopravu, osoby "
    "a další skutečnosti, které se na pracovišti vyskytují."
)

HAZARD_INVENTORY_CATEGORY_EQUIPMENT = "equipment"
HAZARD_INVENTORY_CATEGORY_ACTIVITY = "activity"
HAZARD_INVENTORY_CATEGORY_ENERGY = "energy"
HAZARD_INVENTORY_CATEGORY_SUBSTANCE = "substance"
HAZARD_INVENTORY_CATEGORY_STRUCTURE = "structure"
HAZARD_INVENTORY_CATEGORY_TRANSPORT = "transport"
HAZARD_INVENTORY_CATEGORY_PERSON = "person"
HAZARD_INVENTORY_CATEGORY_ENVIRONMENT = "environment"
HAZARD_INVENTORY_CATEGORY_OTHER = "other"

HAZARD_INVENTORY_CATEGORIES = (
    HAZARD_INVENTORY_CATEGORY_EQUIPMENT,
    HAZARD_INVENTORY_CATEGORY_ACTIVITY,
    HAZARD_INVENTORY_CATEGORY_ENERGY,
    HAZARD_INVENTORY_CATEGORY_SUBSTANCE,
    HAZARD_INVENTORY_CATEGORY_STRUCTURE,
    HAZARD_INVENTORY_CATEGORY_TRANSPORT,
    HAZARD_INVENTORY_CATEGORY_PERSON,
    HAZARD_INVENTORY_CATEGORY_ENVIRONMENT,
    HAZARD_INVENTORY_CATEGORY_OTHER,
)

HAZARD_INVENTORY_CATEGORY_LABELS = {
    HAZARD_INVENTORY_CATEGORY_EQUIPMENT: "Stroje a zařízení",
    HAZARD_INVENTORY_CATEGORY_ACTIVITY: "Činnosti",
    HAZARD_INVENTORY_CATEGORY_ENERGY: "Energie",
    HAZARD_INVENTORY_CATEGORY_SUBSTANCE: "Látky a materiály",
    HAZARD_INVENTORY_CATEGORY_STRUCTURE: "Prostory a konstrukce",
    HAZARD_INVENTORY_CATEGORY_TRANSPORT: "Doprava",
    HAZARD_INVENTORY_CATEGORY_PERSON: "Osoby",
    HAZARD_INVENTORY_CATEGORY_ENVIRONMENT: "Podmínky prostředí",
    HAZARD_INVENTORY_CATEGORY_OTHER: "Ostatní",
}

READ_ONLY_IDENTIFICATION_STATUSES = (
    HAZARD_IDENTIFICATION_STATUS_COMPLETED,
    HAZARD_IDENTIFICATION_STATUS_ARCHIVED,
)

INVENTORY_ITEM_DIALOG_TITLE = "Položka inventury"

INVENTORY_COL_ID = 0
INVENTORY_COL_NAME = 1
INVENTORY_COL_DESCRIPTION = 2
INVENTORY_COL_ACTIVE = 3
INVENTORY_COLUMN_COUNT = 4

INVENTORY_TABLE_HEADERS = ["ID", "Název", "Popis", "Aktivní"]

HAZARD_INVENTORY_RELATION_ACTIVITY = "activity"
HAZARD_INVENTORY_RELATION_ENERGY = "energy"
HAZARD_INVENTORY_RELATION_SUBSTANCE = "substance"
HAZARD_INVENTORY_RELATION_PERSON = "person"
HAZARD_INVENTORY_RELATION_ENVIRONMENT = "environment"
HAZARD_INVENTORY_RELATION_TRANSPORT = "transport"
HAZARD_INVENTORY_RELATION_STRUCTURE = "structure"
HAZARD_INVENTORY_RELATION_EQUIPMENT = "equipment"
HAZARD_INVENTORY_RELATION_OTHER = "other"

HAZARD_INVENTORY_RELATION_TYPES = (
    HAZARD_INVENTORY_RELATION_ACTIVITY,
    HAZARD_INVENTORY_RELATION_ENERGY,
    HAZARD_INVENTORY_RELATION_SUBSTANCE,
    HAZARD_INVENTORY_RELATION_PERSON,
    HAZARD_INVENTORY_RELATION_ENVIRONMENT,
    HAZARD_INVENTORY_RELATION_TRANSPORT,
    HAZARD_INVENTORY_RELATION_STRUCTURE,
    HAZARD_INVENTORY_RELATION_EQUIPMENT,
    HAZARD_INVENTORY_RELATION_OTHER,
)

HAZARD_INVENTORY_RELATION_TYPE_LABELS = {
    HAZARD_INVENTORY_RELATION_ACTIVITY: "Související činnost",
    HAZARD_INVENTORY_RELATION_ENERGY: "Související energie",
    HAZARD_INVENTORY_RELATION_SUBSTANCE: "Související látka nebo materiál",
    HAZARD_INVENTORY_RELATION_PERSON: "Ohrožená / přítomná osoba",
    HAZARD_INVENTORY_RELATION_ENVIRONMENT: "Podmínka prostředí",
    HAZARD_INVENTORY_RELATION_TRANSPORT: "Související doprava",
    HAZARD_INVENTORY_RELATION_STRUCTURE: "Související prostor nebo konstrukce",
    HAZARD_INVENTORY_RELATION_EQUIPMENT: "Související zařízení",
    HAZARD_INVENTORY_RELATION_OTHER: "Jiná souvislost",
}

HAZARD_INVENTORY_RELATION_TARGET_CATEGORY = {
    HAZARD_INVENTORY_RELATION_ACTIVITY: HAZARD_INVENTORY_CATEGORY_ACTIVITY,
    HAZARD_INVENTORY_RELATION_ENERGY: HAZARD_INVENTORY_CATEGORY_ENERGY,
    HAZARD_INVENTORY_RELATION_SUBSTANCE: HAZARD_INVENTORY_CATEGORY_SUBSTANCE,
    HAZARD_INVENTORY_RELATION_PERSON: HAZARD_INVENTORY_CATEGORY_PERSON,
    HAZARD_INVENTORY_RELATION_ENVIRONMENT: HAZARD_INVENTORY_CATEGORY_ENVIRONMENT,
    HAZARD_INVENTORY_RELATION_TRANSPORT: HAZARD_INVENTORY_CATEGORY_TRANSPORT,
    HAZARD_INVENTORY_RELATION_STRUCTURE: HAZARD_INVENTORY_CATEGORY_STRUCTURE,
    HAZARD_INVENTORY_RELATION_EQUIPMENT: HAZARD_INVENTORY_CATEGORY_EQUIPMENT,
    HAZARD_INVENTORY_RELATION_OTHER: HAZARD_INVENTORY_CATEGORY_OTHER,
}

INVENTORY_ANALYSIS_TITLE = "Analýza položky"
INVENTORY_RELATION_DIALOG_TITLE = "Souvislost inventury"

RELATION_COL_ID = 0
RELATION_COL_TYPE = 1
RELATION_COL_CATEGORY = 2
RELATION_COL_NAME = 3
RELATION_COL_NOTE = 4
RELATION_COL_ACTIVE = 5
RELATION_COLUMN_COUNT = 6

RELATION_TABLE_HEADERS = [
    "ID",
    "Typ souvislosti",
    "Kategorie",
    "Název",
    "Poznámka",
    "Aktivní",
]


def inventory_relation_target_category(relation_type: str) -> str | None:
    return HAZARD_INVENTORY_RELATION_TARGET_CATEGORY.get(relation_type)


def is_identification_inventory_read_only(status: str) -> bool:
    return status in READ_ONLY_IDENTIFICATION_STATUSES
