TAB_SUMMARY = "Souhrn"
TAB_BACKUP = "Zálohování"
TAB_TRANSFER = "Přenos dat"
TAB_CODEBOOKS = "Číselníky"
TAB_DIAGNOSTICS = "Diagnostika"

TAB_ORDER = (
    TAB_SUMMARY,
    TAB_BACKUP,
    TAB_TRANSFER,
    TAB_CODEBOOKS,
    TAB_DIAGNOSTICS,
)
