TASK_TYPE_CORRECTIVE = "corrective"
TASK_TYPE_INVESTIGATION_ACTION = "investigation_action"

DEFAULT_TASK_TYPE = TASK_TYPE_CORRECTIVE

TASK_TYPES = (
    TASK_TYPE_CORRECTIVE,
    TASK_TYPE_INVESTIGATION_ACTION,
)

TASK_TYPE_LABELS = {
    TASK_TYPE_CORRECTIVE: "Nápravné opatření",
    TASK_TYPE_INVESTIGATION_ACTION: "Vyšetřovací úkon",
}
