TASK_TYPE_CORRECTIVE = "corrective"
TASK_TYPE_INVESTIGATION_ACTION = "investigation_action"
TASK_TYPE_ADMINISTRATIVE = "administrative"
TASK_TYPE_CONTROL = "control"
TASK_TYPE_AUDIT = "audit"

DEFAULT_TASK_TYPE = TASK_TYPE_CORRECTIVE

TASK_TYPES = (
    TASK_TYPE_CORRECTIVE,
    TASK_TYPE_INVESTIGATION_ACTION,
    TASK_TYPE_ADMINISTRATIVE,
    TASK_TYPE_CONTROL,
    TASK_TYPE_AUDIT,
)

TASK_TYPE_LABELS = {
    TASK_TYPE_CORRECTIVE: "Nápravné opatření",
    TASK_TYPE_INVESTIGATION_ACTION: "Vyšetřovací úkon",
    TASK_TYPE_ADMINISTRATIVE: "Administrativní úkol",
    TASK_TYPE_CONTROL: "Kontrolní úkon",
    TASK_TYPE_AUDIT: "Auditní úkol",
}
