"""Metadata a konstanty modulu Prověrky BOZP."""

from dataclasses import dataclass

MODULE_KEY = "proverky"
MODULE_NAME = "Prověrky BOZP"
MODULE_DESCRIPTION = "Roční prověrky BOZP/PO na pracovištích."

INSPECTION_STATUS_PLANOVANO = "Plánováno"
INSPECTION_STATUS_PROBIHA = "Probíhá"
INSPECTION_STATUS_DOKONCENO = "Dokončeno"

INSPECTION_SPIS_STATUSES = (
    INSPECTION_STATUS_PLANOVANO,
    INSPECTION_STATUS_PROBIHA,
    INSPECTION_STATUS_DOKONCENO,
)

DEFAULT_INSPECTION_SPIS_STATUS = INSPECTION_STATUS_PLANOVANO

INSPECTION_TYPE_RADNA = "Řádná"
INSPECTION_TYPE_MIMORADNA = "Mimořádná"

INSPECTION_TYPES = (
    INSPECTION_TYPE_RADNA,
    INSPECTION_TYPE_MIMORADNA,
)

DEFAULT_INSPECTION_TYPE = INSPECTION_TYPE_RADNA

PLANNED_MONTH_NAMES = (
    "leden",
    "únor",
    "březen",
    "duben",
    "květen",
    "červen",
    "červenec",
    "srpen",
    "září",
    "říjen",
    "listopad",
    "prosinec",
)

PLANNED_MONTH_NOT_SET_LABEL = "—"
INSPECTION_STATUS_PLANOVANA = INSPECTION_STATUS_PLANOVANO
INSPECTION_STATUS_DOKONCENA = INSPECTION_STATUS_DOKONCENO
INSPECTION_STATUS_UZAVRENA = INSPECTION_STATUS_DOKONCENO
DEFAULT_INSPECTION_STATUS = DEFAULT_INSPECTION_SPIS_STATUS

VALID_INSPECTION_STATUSES = frozenset(INSPECTION_SPIS_STATUSES)

INSPECTION_STATUS_FILTER_PROBIHAJICI = "Probíhající"
INSPECTION_STATUS_FILTER_PLANOVANE = "Plánované"
INSPECTION_STATUS_FILTER_DOKONCENE = "Dokončené"
INSPECTION_STATUS_FILTER_VSE = "Vše"

DEFAULT_INSPECTION_STATUS_FILTER = INSPECTION_STATUS_FILTER_PROBIHAJICI

INSPECTION_STATUS_BY_FILTER = {
    INSPECTION_STATUS_FILTER_PROBIHAJICI: INSPECTION_STATUS_PROBIHA,
    INSPECTION_STATUS_FILTER_PLANOVANE: INSPECTION_STATUS_PLANOVANO,
    INSPECTION_STATUS_FILTER_DOKONCENE: INSPECTION_STATUS_DOKONCENO,
}

YEAR_FILTER_VSE = "Vše"

TAB_KONTROLOVANE_OBLASTI = "Kontrolované oblasti"

TAB_LABELS = (
    "Spis",
    "Komise",
    TAB_KONTROLOVANE_OBLASTI,
    "Zjištění",
    "Úkoly",
    "Přílohy",
    "Závěr",
)

AREA_PANEL_LEFT_WIDTH = 260
AREA_NOT_IMPLEMENTED_TEXT = "Tato oblast zatím není implementována."
AREA_PART_NOT_IMPLEMENTED_TEXT = "Tato část bude doplněna."
KNOWLEDGE_BLOCK_NOT_IMPLEMENTED_TEXT = "Tato část bude doplněna."

FINDING_SOURCE_LABEL = "Prověrka BOZP"
FINDING_DIALOG_TITLE = "Zjištění prověrky BOZP"
FINDING_CREATE_FROM_CONTROL_POINT_LABEL = "➕ Založit zjištění"
INSPECTION_MUST_BE_SAVED_MESSAGE = "Prověrku je nutné nejdříve uložit."


@dataclass(frozen=True)
class ProverkyFindingKnowledgeContext:
    area_id: str
    area_label: str
    section_id: str
    section_label: str
    control_point_id: str
    control_point_label: str
