"""Metadata a konstanty modulu Prověrky BOZP."""

MODULE_KEY = "proverky"
MODULE_NAME = "Prověrky BOZP"
MODULE_DESCRIPTION = "Roční prověrky BOZP/PO na pracovištích."

INSPECTION_STATUS_PLANOVANA = "Plánovaná"
INSPECTION_STATUS_PROBIHA = "Probíhá"
INSPECTION_STATUS_DOKONCENA = "Dokončena"
INSPECTION_STATUS_SE_ZAVADAMI = "Se závadami"
INSPECTION_STATUS_UZAVRENA = "Uzavřena"

DEFAULT_INSPECTION_STATUS = INSPECTION_STATUS_PLANOVANA

VALID_INSPECTION_STATUSES = frozenset(
    {
        INSPECTION_STATUS_PLANOVANA,
        INSPECTION_STATUS_PROBIHA,
        INSPECTION_STATUS_DOKONCENA,
        INSPECTION_STATUS_SE_ZAVADAMI,
        INSPECTION_STATUS_UZAVRENA,
    }
)

INSPECTION_STATUS_FILTER_PROBIHAJICI = "Probíhající"
INSPECTION_STATUS_FILTER_PLANOVANE = "Plánované"
INSPECTION_STATUS_FILTER_DOKONCENE = "Dokončené"
INSPECTION_STATUS_FILTER_VSE = "Vše"

DEFAULT_INSPECTION_STATUS_FILTER = INSPECTION_STATUS_FILTER_PROBIHAJICI

INSPECTION_STATUS_BY_FILTER = {
    INSPECTION_STATUS_FILTER_PROBIHAJICI: INSPECTION_STATUS_PROBIHA,
    INSPECTION_STATUS_FILTER_PLANOVANE: INSPECTION_STATUS_PLANOVANA,
    INSPECTION_STATUS_FILTER_DOKONCENE: INSPECTION_STATUS_UZAVRENA,
}

YEAR_FILTER_VSE = "Vše"

TAB_LABELS = (
    "Spis",
    "Komise",
    "Průběh prověrky",
    "Zjištění",
    "Úkoly",
    "Přílohy",
    "Závěr",
)
