"""Metadata a konstanty modulu Prověrky BOZP."""

from dataclasses import dataclass

MODULE_KEY = "proverky"
MODULE_NAME = "Prověrky BOZP"
MODULE_DESCRIPTION = "Roční prověrky BOZP/PO na pracovištích."

INSPECTION_STATUS_PLANOVANO = "Plánováno"
INSPECTION_STATUS_PROBIHA = "Probíhá"
INSPECTION_STATUS_DOKONCENO = "Dokončeno"

INSPECTION_SPIS_STATUSES = (
    INSPECTION_STATUS_PLANOVANO,
    INSPECTION_STATUS_PROBIHA,
    INSPECTION_STATUS_DOKONCENO,
)

DEFAULT_INSPECTION_SPIS_STATUS = INSPECTION_STATUS_PLANOVANO

INSPECTION_TYPE_RADNA = "Řádná"
INSPECTION_TYPE_MIMORADNA = "Mimořádná"

INSPECTION_TYPES = (
    INSPECTION_TYPE_RADNA,
    INSPECTION_TYPE_MIMORADNA,
)

DEFAULT_INSPECTION_TYPE = INSPECTION_TYPE_RADNA

PLANNED_MONTH_NAMES = (
    "leden",
    "únor",
    "březen",
    "duben",
    "květen",
    "červen",
    "červenec",
    "srpen",
    "září",
    "říjen",
    "listopad",
    "prosinec",
)

PLANNED_MONTH_NOT_SET_LABEL = "—"
INSPECTION_STATUS_PLANOVANA = INSPECTION_STATUS_PLANOVANO
INSPECTION_STATUS_DOKONCENA = INSPECTION_STATUS_DOKONCENO
INSPECTION_STATUS_UZAVRENA = INSPECTION_STATUS_DOKONCENO
DEFAULT_INSPECTION_STATUS = DEFAULT_INSPECTION_SPIS_STATUS

VALID_INSPECTION_STATUSES = frozenset(INSPECTION_SPIS_STATUSES)

INSPECTION_STATUS_FILTER_PROBIHAJICI = "Probíhající"
INSPECTION_STATUS_FILTER_PLANOVANE = "Plánované"
INSPECTION_STATUS_FILTER_DOKONCENE = "Dokončené"
INSPECTION_STATUS_FILTER_VSE = "Vše"

DEFAULT_INSPECTION_STATUS_FILTER = INSPECTION_STATUS_FILTER_PROBIHAJICI

INSPECTION_STATUS_BY_FILTER = {
    INSPECTION_STATUS_FILTER_PROBIHAJICI: INSPECTION_STATUS_PROBIHA,
    INSPECTION_STATUS_FILTER_PLANOVANE: INSPECTION_STATUS_PLANOVANO,
    INSPECTION_STATUS_FILTER_DOKONCENE: INSPECTION_STATUS_DOKONCENO,
}

YEAR_FILTER_VSE = "Vše"

TAB_KONTROLOVANE_OBLASTI = "Kontrolované oblasti"

TAB_LABELS = (
    "Spis",
    "Komise",
    TAB_KONTROLOVANE_OBLASTI,
    "Zjištění",
    "Úkoly",
    "Přílohy",
    "Závěr",
)

AREA_PANEL_LEFT_WIDTH = 260
AREA_NOT_IMPLEMENTED_TEXT = "Tato oblast zatím není implementována."
AREA_PART_NOT_IMPLEMENTED_TEXT = "Tato část bude doplněna."
KNOWLEDGE_BLOCK_NOT_IMPLEMENTED_TEXT = "Tato část bude doplněna."

FINDING_SOURCE_LABEL = "Prověrka BOZP"
FINDING_DIALOG_TITLE = "Zjištění prověrky BOZP"
FINDING_CREATE_FROM_CONTROL_POINT_LABEL = "➕ Založit zjištění"
FINDING_OPEN_EXISTING_LABEL = "Otevřít zjištění"
FINDING_CREATED_LABEL = "Zjištění založeno"
FINDING_DUPLICATE_MESSAGE = "Pro tento kontrolní bod už existuje zjištění. Otevře se existující záznam."
INSPECTION_MUST_BE_SAVED_MESSAGE = "Prověrku je nutné nejdříve uložit."
FINDING_REQUIRES_NONCOMPLIANCE_MESSAGE = "Zjištění lze založit pouze u kontrolního bodu s výsledkem „Nevyhovuje“."

CONTROL_POINT_HISTORY_EMPTY = "Zatím bez historie."
CONTROL_POINT_HISTORY_SELECT = "Vyberte kontrolní bod vlevo."
CONTROL_POINT_HISTORY_LIMIT = 5
CONTROL_POINT_HISTORY_WORKPLACE_TITLE = "Historie tohoto pracoviště"
CONTROL_POINT_SHARED_EXPERIENCES_TITLE = "Sdílené zkušenosti"
CONTROL_POINT_HISTORY_WORKPLACE_NO_WORKPLACE = "Pro zobrazení historie vyberte pracoviště."
CONTROL_POINT_SHARED_EXPERIENCES_EMPTY = "Zatím bez sdílených zkušeností."

KNOWLEDGE_EDITOR_BUTTON_LABEL = "Editor znalostí"
KNOWLEDGE_EDIT_FROM_CARD_LABEL = "✏ Upravit znalosti"
KNOWLEDGE_POSTUP_KONTROLY_TITLE = "Postup kontroly"
KNOWLEDGE_CONTROL_PROCEDURE_BUTTON_LABEL = "📋 Doporučený postup kontroly"
KNOWLEDGE_CONTROL_PROCEDURE_DIALOG_TITLE = "📋 Doporučený postup kontroly"
KNOWLEDGE_REFERENCE_PHOTOS_TITLE = "📷 Referenční fotografie"
REFERENCE_PHOTO_THUMBNAIL_SIZE = 120
REFERENCE_PHOTO_PLACEHOLDER_WIDTH = 220
REFERENCE_PHOTO_PLACEHOLDER_ICON_SIZE_PX = 40
REFERENCE_PHOTO_FILTER = "Obrázky (*.jpg *.jpeg *.png *.webp *.heic *.heif);;Všechny soubory (*.*)"
KNOWLEDGE_EDITOR_DEFAULT_AREA_ID = "prvni_pomoc"
KNOWLEDGE_EDITOR_DEFAULT_SECTION_ID = "lekarnicka"


@dataclass(frozen=True)
class ProverkyFindingKnowledgeContext:
    area_id: str
    area_label: str
    section_id: str
    section_label: str
    control_point_id: str
    control_point_label: str
