from core.shared.constants import ACCIDENT_FINDING_TYPES

MU_STATUS_PROBIHA = "Probíhá"
MU_STATUS_DOKONCENO = "Dokončeno"
MU_STATUS_ODLOZENO = "Odloženo"

DEFAULT_MU_STATUS = MU_STATUS_PROBIHA

VALID_MU_STATUSES = frozenset(
    {
        MU_STATUS_PROBIHA,
        MU_STATUS_DOKONCENO,
        MU_STATUS_ODLOZENO,
    }
)

MU_STATUS_FILTER_PROBIHA = "Probíhá"
MU_STATUS_FILTER_DOKONCENO = "Dokončeno"
MU_STATUS_FILTER_ODLOZENO = "Odloženo"
MU_STATUS_FILTER_VSE = "Vše"

DEFAULT_MU_STATUS_FILTER = MU_STATUS_FILTER_PROBIHA

MU_STATUS_BY_FILTER = {
    MU_STATUS_FILTER_PROBIHA: MU_STATUS_PROBIHA,
    MU_STATUS_FILTER_DOKONCENO: MU_STATUS_DOKONCENO,
    MU_STATUS_FILTER_ODLOZENO: MU_STATUS_ODLOZENO,
}

EVENT_CHARACTER_URAZ = "Úraz"
EVENT_CHARACTER_POSKOZENI_ZARIZENI = "Poškození zařízení"
EVENT_CHARACTER_NEHODA_ZELEZNICE = "Nehoda na železnici"
EVENT_CHARACTER_PORUSENI_BOZP = "Porušení BOZP"
EVENT_CHARACTER_JINA_MU = "Jiná mimořádná událost"

DEFAULT_EVENT_CHARACTER = EVENT_CHARACTER_JINA_MU

EVENT_CHARACTERS = (
    EVENT_CHARACTER_URAZ,
    EVENT_CHARACTER_POSKOZENI_ZARIZENI,
    EVENT_CHARACTER_NEHODA_ZELEZNICE,
    EVENT_CHARACTER_PORUSENI_BOZP,
    EVENT_CHARACTER_JINA_MU,
)

SOURCE_TYPE_ACCIDENT = "accident"
SOURCE_TYPE_AUDIT = "audit"
SOURCE_TYPE_CONTROL = "control"
SOURCE_TYPE_MANUAL = "manual"
SOURCE_TYPE_OTHER = "other"

DEFAULT_SOURCE_TYPE = SOURCE_TYPE_MANUAL

SOURCE_TYPE_LABELS = {
    SOURCE_TYPE_ACCIDENT: "Kniha úrazů",
    SOURCE_TYPE_AUDIT: "Audit",
    SOURCE_TYPE_CONTROL: "Kontrola",
    SOURCE_TYPE_OTHER: "Jiný podnět",
    SOURCE_TYPE_MANUAL: "Ruční založení",
}

SOURCE_TYPES = (
    SOURCE_TYPE_ACCIDENT,
    SOURCE_TYPE_AUDIT,
    SOURCE_TYPE_CONTROL,
    SOURCE_TYPE_OTHER,
    SOURCE_TYPE_MANUAL,
)

SOURCE_TYPES_WITH_RECORD = frozenset(
    {
        SOURCE_TYPE_ACCIDENT,
        SOURCE_TYPE_AUDIT,
        SOURCE_TYPE_CONTROL,
    }
)

SOURCE_TYPES_WITH_TEXT = frozenset(
    {
        SOURCE_TYPE_OTHER,
    }
)

MU_INVESTIGATION_FINDING_TYPES = ACCIDENT_FINDING_TYPES

YEAR_FILTER_VSE = "Vše"
