WORKPLACE_ITEM_TYPE_OPERATION = "operation"
WORKPLACE_ITEM_TYPE_WORKPLACE = "workplace"
WORKPLACE_ITEM_TYPE_WORKPLACE_PART = "workplace_part"

WORKPLACE_ITEM_TYPES = (
    WORKPLACE_ITEM_TYPE_OPERATION,
    WORKPLACE_ITEM_TYPE_WORKPLACE,
    WORKPLACE_ITEM_TYPE_WORKPLACE_PART,
)

WORKPLACE_ITEM_TYPE_LABELS = {
    WORKPLACE_ITEM_TYPE_OPERATION: "Provoz",
    WORKPLACE_ITEM_TYPE_WORKPLACE: "Pracoviště",
    WORKPLACE_ITEM_TYPE_WORKPLACE_PART: "Část pracoviště",
}

WORKPLACE_ITEM_TYPE_ORDER = {
    WORKPLACE_ITEM_TYPE_OPERATION: 0,
    WORKPLACE_ITEM_TYPE_WORKPLACE: 1,
    WORKPLACE_ITEM_TYPE_WORKPLACE_PART: 2,
}

WORKPLACE_PARENT_TYPE = {
    WORKPLACE_ITEM_TYPE_OPERATION: None,
    WORKPLACE_ITEM_TYPE_WORKPLACE: WORKPLACE_ITEM_TYPE_OPERATION,
    WORKPLACE_ITEM_TYPE_WORKPLACE_PART: WORKPLACE_ITEM_TYPE_WORKPLACE,
}
