"""Konstanty Periodických činností."""

MODULE_KEY = "periodicke_cinnosti"
MODULE_NAME = "Periodické činnosti"

PLACE_KIND_WORKPLACE = "workplace"
PLACE_KIND_ORGANIZATION = "organization"
PLACE_KIND_OTHER = "other"
PLACE_KIND_NONE = "none"

PLACE_KINDS = (
    PLACE_KIND_WORKPLACE,
    PLACE_KIND_ORGANIZATION,
    PLACE_KIND_OTHER,
    PLACE_KIND_NONE,
)

UNIT_DAYS = "days"
UNIT_WEEKS = "weeks"
UNIT_MONTHS = "months"
UNIT_YEARS = "years"

TIME_UNITS = (
    UNIT_DAYS,
    UNIT_WEEKS,
    UNIT_MONTHS,
    UNIT_YEARS,
)

NEXT_FROM_PLANNED = "planned"
NEXT_FROM_ACTUAL = "actual"

NEXT_FROM_VALUES = (
    NEXT_FROM_PLANNED,
    NEXT_FROM_ACTUAL,
)

DEFAULT_PLACE_KIND = PLACE_KIND_NONE
DEFAULT_REPEAT_EVERY = 1
DEFAULT_REPEAT_UNIT = UNIT_YEARS
DEFAULT_NOTIFY_EVERY = 0
DEFAULT_NOTIFY_UNIT = UNIT_DAYS
DEFAULT_NEXT_FROM = NEXT_FROM_PLANNED
