"""Společná infrastruktura formátu, tvorby, kontroly a obnovy ``*.mbbackup``.

BACKUP-1a: konstanty, cesty, SHA-256, metadata.
BACKUP-1b: vytvoření úplné zálohy instance.
BACKUP-1c: důkladné ověření integrity balíčku.
BACKUP-2a: bezpečná obnova instance (bez UI).
BACKUP-2d: ověření úplnosti zálohy.
"""

from core.backup.workspace_roots import (
    BACKUP_WORKSPACE_ROOTS,
    NON_BACKUP_WORKSPACE_ROOTS,
    SNAPSHOT_SUPPORT_PHOTOS_DIR,
    SNAPSHOT_SUPPORT_PHOTOS_LIMITATION,
    classify_workspace_roots,
    package_covers_snapshot_support_photos,
)
from core.backup.completeness import (
    VERDICT_COMPLETE,
    VERDICT_COMPLETE_WITH_LIMITATIONS,
    VERDICT_INCOMPLETE,
    compare_instances,
    inventory_workspace_files,
    scan_absolute_paths,
)
from core.backup.constants import (
    BACKUP_EXTENSION,
    BACKUP_FORMAT_VERSION,
    COMPONENT_DATABASE,
    COMPONENT_METADATA,
    COMPONENT_SETTINGS,
    COMPONENT_WORKSPACE,
    INTEGRITY_INVALID,
    INTEGRITY_VALID,
    INTEGRITY_VALID_WITH_WARNINGS,
    ISSUE_SEVERITY_ERROR,
    ISSUE_SEVERITY_WARNING,
    METADATA_FILENAME,
    PACKAGE_KIND_INSTANCE_BACKUP,
    PACKAGE_KIND_RISK_CATALOG_EXPORT,
    PACKAGE_STATUS_COMPLETE,
    PACKAGE_STATUS_CREATING,
    REQUIRED_ARCHIVE_ROOTS,
    RESTORE_ERR_BAD_ARCHIVE,
    RESTORE_ERR_DISK_FULL,
    RESTORE_ERR_FAILED_AFTER_SWAP_ROLLED_BACK,
    RESTORE_ERR_FAILED_BEFORE_SWAP,
    RESTORE_ERR_INTEGRITY,
    RESTORE_ERR_INTERRUPTED,
    RESTORE_ERR_INVALID_DATABASE,
    RESTORE_ERR_INVALID_METADATA,
    RESTORE_ERR_MISSING_COMPONENT,
    RESTORE_ERR_POSTCHECK,
    RESTORE_ERR_ROLLBACK_FAILED,
    RESTORE_ERR_UNSAFE_PATH,
    RESTORE_ERR_WRITE_ERROR,
    SUPPORTED_BACKUP_FORMAT_VERSIONS,
    SUPPORTED_PACKAGE_KINDS,
)
from core.backup.hashing import hashes_equal, sha256_bytes, sha256_file, sha256_stream
from core.backup.metadata import (
    BackupFileEntry,
    BackupMetadata,
    BackupMetadataError,
    build_file_entry,
    create_backup_metadata,
    mark_package_complete,
    validate_backup_metadata,
)
from core.backup.package_create import (
    DEFAULT_WORKSPACE_EXCLUDE_DIRS,
    DEFAULT_WORKSPACE_INCLUDE_DIRS,
    CreateInstanceBackupResult,
    InstanceBackupError,
    auto_before_restore_backup_filename,
    create_instance_backup,
    default_instance_backup_filename,
)
from core.backup.package_extract import SafeExtractError, safe_extract_zip_member
from core.backup.package_integrity import (
    BackupIntegrityIssue,
    BackupIntegrityReport,
    BackupPackageVerificationError,
    assert_backup_integrity,
    inspect_backup_integrity,
)
from core.backup.package_restore import (
    InstanceRestoreError,
    RestoreInstanceBackupResult,
    restore_instance_backup,
)
from core.backup.recovery_marker import (
    build_recovery_marker_payload,
    find_recovery_markers,
    read_recovery_marker,
    recovery_marker_path,
    write_recovery_marker,
)
from core.backup.package_verify import (
    package_looks_like_mbbackup,
    read_backup_metadata_from_package,
    verify_instance_backup_package,
)
from core.backup.paths import (
    BackupPathError,
    component_for_archive_path,
    is_safe_archive_path,
    normalize_archive_path,
)
from core.backup.sqlite_snapshot import (
    SqliteSnapshotError,
    create_sqlite_snapshot,
    inspect_sqlite_file,
    is_sqlite_database_empty,
    read_sqlite_user_version,
    sqlite_integrity_check,
    sqlite_quick_check,
)

__all__ = [
    "BACKUP_EXTENSION",
    "BACKUP_FORMAT_VERSION",
    "BACKUP_WORKSPACE_ROOTS",
    "NON_BACKUP_WORKSPACE_ROOTS",
    "SNAPSHOT_SUPPORT_PHOTOS_DIR",
    "SNAPSHOT_SUPPORT_PHOTOS_LIMITATION",
    "classify_workspace_roots",
    "package_covers_snapshot_support_photos",
    "VERDICT_COMPLETE",
    "VERDICT_COMPLETE_WITH_LIMITATIONS",
    "VERDICT_INCOMPLETE",
    "compare_instances",
    "inventory_workspace_files",
    "scan_absolute_paths",
    "COMPONENT_DATABASE",
    "COMPONENT_METADATA",
    "COMPONENT_SETTINGS",
    "COMPONENT_WORKSPACE",
    "DEFAULT_WORKSPACE_EXCLUDE_DIRS",
    "DEFAULT_WORKSPACE_INCLUDE_DIRS",
    "INTEGRITY_INVALID",
    "INTEGRITY_VALID",
    "INTEGRITY_VALID_WITH_WARNINGS",
    "ISSUE_SEVERITY_ERROR",
    "ISSUE_SEVERITY_WARNING",
    "METADATA_FILENAME",
    "PACKAGE_KIND_INSTANCE_BACKUP",
    "PACKAGE_KIND_RISK_CATALOG_EXPORT",
    "PACKAGE_STATUS_COMPLETE",
    "PACKAGE_STATUS_CREATING",
    "REQUIRED_ARCHIVE_ROOTS",
    "RESTORE_ERR_BAD_ARCHIVE",
    "RESTORE_ERR_DISK_FULL",
    "RESTORE_ERR_FAILED_AFTER_SWAP_ROLLED_BACK",
    "RESTORE_ERR_FAILED_BEFORE_SWAP",
    "RESTORE_ERR_INTEGRITY",
    "RESTORE_ERR_INTERRUPTED",
    "RESTORE_ERR_INVALID_DATABASE",
    "RESTORE_ERR_INVALID_METADATA",
    "RESTORE_ERR_MISSING_COMPONENT",
    "RESTORE_ERR_POSTCHECK",
    "RESTORE_ERR_ROLLBACK_FAILED",
    "RESTORE_ERR_UNSAFE_PATH",
    "RESTORE_ERR_WRITE_ERROR",
    "SUPPORTED_BACKUP_FORMAT_VERSIONS",
    "SUPPORTED_PACKAGE_KINDS",
    "BackupFileEntry",
    "BackupIntegrityIssue",
    "BackupIntegrityReport",
    "BackupMetadata",
    "BackupMetadataError",
    "BackupPackageVerificationError",
    "BackupPathError",
    "CreateInstanceBackupResult",
    "InstanceBackupError",
    "InstanceRestoreError",
    "RestoreInstanceBackupResult",
    "SafeExtractError",
    "SqliteSnapshotError",
    "assert_backup_integrity",
    "build_file_entry",
    "component_for_archive_path",
    "create_backup_metadata",
    "auto_before_restore_backup_filename",
    "create_instance_backup",
    "create_sqlite_snapshot",
    "default_instance_backup_filename",
    "find_recovery_markers",
    "hashes_equal",
    "inspect_backup_integrity",
    "inspect_sqlite_file",
    "is_safe_archive_path",
    "is_sqlite_database_empty",
    "mark_package_complete",
    "normalize_archive_path",
    "package_looks_like_mbbackup",
    "read_backup_metadata_from_package",
    "read_recovery_marker",
    "read_sqlite_user_version",
    "recovery_marker_path",
    "restore_instance_backup",
    "safe_extract_zip_member",
    "sha256_bytes",
    "sha256_file",
    "sha256_stream",
    "sqlite_integrity_check",
    "sqlite_quick_check",
    "validate_backup_metadata",
    "verify_instance_backup_package",
    "write_recovery_marker",
    "build_recovery_marker_payload",
]
