"""Konstanty modulu Koordinace BOZP."""

MODULE_KEY = "koordinace_bozp"
MODULE_NAME = "Koordinace BOZP"
MODULE_DESCRIPTION = (
    "Evidence koordinačních schůzek BOZP podle § 101 odst. 3 zákoníku práce."
)

DIALOG_WINDOW_TITLE = "Koordinace BOZP"

BOZP_COORDINATION_STATUS_DRAFT = "draft"
BOZP_COORDINATION_STATUS_COMPLETED = "completed"
BOZP_COORDINATION_STATUS_ARCHIVED = "archived"

BOZP_COORDINATION_STATUSES = (
    BOZP_COORDINATION_STATUS_DRAFT,
    BOZP_COORDINATION_STATUS_COMPLETED,
    BOZP_COORDINATION_STATUS_ARCHIVED,
)

DEFAULT_BOZP_COORDINATION_STATUS = BOZP_COORDINATION_STATUS_DRAFT

BOZP_COORDINATION_STATUS_LABELS = {
    BOZP_COORDINATION_STATUS_DRAFT: "Rozpracováno",
    BOZP_COORDINATION_STATUS_COMPLETED: "Dokončeno",
    BOZP_COORDINATION_STATUS_ARCHIVED: "Archivováno",
}

TAB_BASICS = "Základní údaje"
TAB_EMPLOYERS = "Zúčastnění zaměstnavatelé"
TAB_PARTICIPANTS = "Účastníci schůzky"

COORDINATION_EMPLOYER_TYPE_MAIN = "main"
COORDINATION_EMPLOYER_TYPE_PARTICIPANT = "participant"

COORDINATION_EMPLOYER_TYPES = (
    COORDINATION_EMPLOYER_TYPE_MAIN,
    COORDINATION_EMPLOYER_TYPE_PARTICIPANT,
)

COORDINATION_PARTICIPANT_SOURCE_EMPLOYEE = "employee"
COORDINATION_PARTICIPANT_SOURCE_MANUAL = "manual"

COORDINATION_PARTICIPANT_SOURCE_TYPES = (
    COORDINATION_PARTICIPANT_SOURCE_EMPLOYEE,
    COORDINATION_PARTICIPANT_SOURCE_MANUAL,
)

EMP_COL_ID = 0
EMP_COL_ABBREVIATION = 1
EMP_COL_NAME = 2
EMP_COL_ICO = 3
EMP_COL_IS_MAIN = 4
EMP_COL_ACTIVE = 5
EMP_COLUMN_COUNT = 6

EMPLOYER_TABLE_HEADERS = [
    "ID",
    "Zkratka",
    "Název",
    "IČO",
    "Hlavní zaměstnavatel",
    "Aktivní",
]

PART_COL_ID = 0
PART_COL_FULL_NAME = 1
PART_COL_ROLE = 2
PART_COL_PHONE = 3
PART_COL_EMAIL = 4
PART_COL_ACTIVE = 5
PART_COLUMN_COUNT = 6

PARTICIPANT_TABLE_HEADERS = [
    "ID",
    "Jméno a příjmení",
    "Funkce / role",
    "Telefon",
    "E-mail",
    "Aktivní",
]

COL_ID = 0
COL_NUMBER = 1
COL_MEETING_DATE = 2
COL_PLACE = 3
COL_SUBJECT = 4
COL_STATUS = 5
COLUMN_COUNT = 6

TABLE_HEADERS = [
    "ID",
    "Číslo",
    "Datum koordinační schůzky",
    "Místo",
    "Předmět koordinace",
    "Stav",
]
